AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'public/system/**/*'
    - 'vendor/bundle/**/*'
Metrics/LineLength:
  Max: 220
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/RegexpLiteral:
  MaxSlashes: 0
Style/Documentation:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Style/Blocks:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 12
